### ISSUE TITLE
Posibility of hide message on say event

### ISSUE THREAD

**Issue by luffynando** [fedddddd/iw5-script#1]
Is there currently a way to hide the message in the say event. As in iw6x with the "/" character but since lua?

**Comment by fedddddd** [comment]
Works the same way on pluto, the / character hides messages from the chat

**Comment by luffynando** [comment]
If I know that, but, add the possibility of hiding the message from lua, even when the "/" character is not used, that is to say, dynamically hide

**Comment by fedddddd** [comment]
Sure, I'll add that tomorrow

**Comment by luffynando** [comment]
thanks for your attention

**Comment by fedddddd** [comment]
I added a function for this, `game:onplayersay(player, message, teamchat)`, which can be used as such:
```lua
game:onplayersay(function(player, message, teamchat)
    if (message == "!test") then
        player:tell("Hello world")
        return true -- Hides the message
    end
end)
```

Note that this is a little different from the say notify because it's not executed on the server frame [as you can see here](https://github.com/fedddddd/iw5-script/blob/main/src/component/notifies.cpp#L197), so functions that do damage like suicide, finishplayerdamage, radiusdamage, etc... will not work correctly unless you wrap them like this:
```lua
game:ontimeout(function()
    player:suicide()
end, 0)
```

**Comment by luffynando** [comment]
thanks, When do you plan the release date?

**Comment by fedddddd** [comment]
Just released the new version
